apiVersion: apps/v1
kind: Deployment
metadata:
  name: exif
  labels:
    app: exif
spec:
  selector:
     matchLabels:
       app: exif
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: exif
    spec:
      containers:
        - image: d0phamin3/exif-service
          imagePullPolicy: Always
          name: exif
          ports:
            - containerPort: 6000
