apiVersion: apps/v1
kind: Deployment
metadata:
  name: textan
  labels:
    app: textan
spec:
  selector:
     matchLabels:
       app: textan
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: textan
    spec:
      containers:
        - image: d0phamin3/textan
          imagePullPolicy: Always
          name: textan
          ports:
            - containerPort: 6001
